#!/usr/bin/perl
use strict;
use warnings;
use autodie;
use lib 'lib';

use JSON;
use Test::More;
use JSON::Schema::Validator::Draft6;

my $test_file = $ARGV[0];
my $test_case_no = $ARGV[1];

my $test_cases;

do {
	local $/;
	open my $fh, '<', $test_file;
	my $data = <$fh>;
	eval { $test_cases = decode_json $data };
	die "Can't parse test file $test_file: $@" if $@;
	close $fh;
};

die "File $test_file doesn't contain array of tests" unless $test_cases && ref $test_cases eq 'ARRAY';

my $tests_quantity = 0;

for ( my $i = 0; $i < scalar @$test_cases; $i++ ) {
	next if defined $test_case_no && $i+1 != $test_case_no;
	$tests_quantity += scalar @{$test_cases->[$i]{tests}};
}

plan tests => $tests_quantity;

my $i = 0;

for ( my $i = 0; $i < scalar @$test_cases; $i++ ) {
	next if defined $test_case_no && $i+1 != $test_case_no;

	my $test_case = $test_cases->[$i];

	for my $t ( @{$test_case->{tests}} ) {
		SKIP: {
			skip $t->{skip}, 1 if $t->{skip};
			my $result = JSON::Schema::Validator::Draft6::validate( $test_case->{schema}, $t->{data} );
			ok $result->{ok} == $t->{valid}, $t->{description};
		}
	}
}

exit 0;
